# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-08-22 06:47:53
"""
import arcpy


def Model():  # 点缓冲

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    points9 = "points9"

    # Process: 缓冲区 (缓冲区) (analysis)
    points9buffer = "E:\\code\\gis\\pro\\pymap\\pymap.gdb\\points9buffer"
    arcpy.analysis.Buffer(in_features=points9, out_feature_class=points9buffer, buffer_distance_or_field="10 Meters",
                          line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"E:\code\gis\pro\pymap\pymap.gdb", workspace=r"E:\code\gis\pro\pymap\pymap.gdb"):
        Model()
